default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=200", "--enforce-all"]
        exclude: yarn.lock
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--write]
        exclude: |
          (?x)^(
              .github/ISSUE_TEMPLATE/bug_report.md|
              .github/ISSUE_TEMPLATE/feature_request.md|
              .github/*.md
          )$

  # TODO
  #- repo: https://github.com/pre-commit/mirrors-eslint
  #  rev: v8.28.0
  #  hooks:
  #    - id: eslint
  #      files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  #      types: [file]
  #      args: ["--fix"]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat_frontmatter

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: PEP8
